DRIVER - Debug mode enabled
PUB<A,B,C> - Successfully initialized publisher object (PUB139635183651136)
PUB<A,B,C> - Try to connect with ZooKeeper server: hosts = 10.0.0.1:2181
PUB<A,B,C> - ZooKeeper Current Status = LOST
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Failed connecting to Zookeeper within the connection retry policy.
PUB<A,B,C> - Exception thrown in start (): <class 'kazoo.handlers.threading.KazooTimeoutError'>
Traceback (most recent call last):
  File "driver.py", line 308, in <module>
    publishers = create_publishers(
  File "driver.py", line 57, in create_publishers
    create_publisher_with_zookeeper(pubs[i])
  File "driver.py", line 14, in create_publisher_with_zookeeper
    publisher.assign_to_zone()
  File "/mnt/dev/assign3/src/lib/publisher.py", line 78, in assign_to_zone
    all_zones = self.zk.get_children("/primaries/")
  File "/usr/lib/python3.8/site-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/lib/python3.8/site-packages/kazoo/handlers/utils.py", line 69, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
