DRIVER - Debug mode enabled
SUB<A,B,C> - Initializing subscriber to centralized broker
SUB<A,B,C> - Successfully initialized subscriber object (SUB139629596260672)
SUB<A,B,C> - Try to connect with ZooKeeper server: hosts = 10.0.0.1:2181
SUB<A,B,C> - ZooKeeper Current Status = LOST
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Failed connecting to Zookeeper within the connection retry policy.
SUB<A,B,C> - Exception thrown in start (): <class 'kazoo.handlers.threading.KazooTimeoutError'>
Traceback (most recent call last):
  File "driver.py", line 337, in <module>
    subscribers = create_subscribers(
  File "driver.py", line 107, in create_subscribers
    create_subscriber_with_zookeeper(subs[i])
  File "driver.py", line 69, in create_subscriber_with_zookeeper
    subscriber.assign_to_zone()
  File "/mnt/dev/assign3/src/lib/subscriber.py", line 82, in assign_to_zone
    all_zones = self.zk.get_children("/primaries/")
  File "/usr/lib/python3.8/site-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/lib/python3.8/site-packages/kazoo/handlers/utils.py", line 69, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
